# This is a basic workflow to help you get started with Actions

name: TODO-actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  TODO-actions:
    runs-on: windows-latest
    steps:
       - name: todo-actions
         uses: dtinth/todo-actions@v0.2.0
